## 行列演算の基礎

esc m is mark down

$\boldsymbol{w} = (\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$

- ベクトルの定義
- 行列の定義
- 転置　
- 逆行列
- 行列積

In [1]:
import numpy as np

In [5]:
# ベクトルの定義
x = np.array([[1],[2],[3]])
print(x)

[[1]
 [2]
 [3]]


In [7]:
# 行列の定義
X = np.array([[1,2],[3,4]])
print(X)

[[1 2]
 [3 4]]


In [10]:
# 転置
Xt = X.T
print(Xt)

[[1 3]
 [2 4]]


In [16]:
# 逆行列
# linear algebra: 線形代数
X_inv = np.linalg.inv(X)
print(X_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [17]:
# 行列積
XX_inv = np.dot(X,X_inv)
print(XX_inv) # roughly 1,0,0,1

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


# よくある間違い

In [20]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [21]:
x.T

array([1, 2, 3])

In [22]:
x = np.array([[1,2,3]])
x

array([[1, 2, 3]])

In [23]:
x.T

array([[1],
       [2],
       [3]])

In [24]:
x = np.array([[[1],[2],[3]]])
x

array([[[1],
        [2],
        [3]]])

# Numpyでよく使う処理

In [30]:
X = np.array([
    [2,3,4],
    [1,2,3]
])

In [31]:
row, col = X.shape

In [32]:
row

2

In [33]:
col

3

In [37]:
for x in X:
    print(x)
    print('-------')

[2 3 4]
-------
[1 2 3]
-------


# 演習問題

$\boldsymbol{X} = \begin{bmatrix}
1 & 2 & 3 \\
1 & 2 & 5 \\
1 & 3 & 4 \\
1 & 5 & 9 \\
\end{bmatrix}
,\ \boldsymbol{y} = \begin{bmatrix}
1\\
5\\
6\\
8\\
\end{bmatrix}
$ のとき

$\boldsymbol{w} = (\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$

- Step1: $\boldsymbol{X}^{T}\boldsymbol{X}$
- Step2: $\boldsymbol{w} = (\boldsymbol{X}^{T}\boldsymbol{X})^{-1}$
- Step3: $\boldsymbol{X}^{T}\boldsymbol{y}$
- Step4: $\boldsymbol{w} = (\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$

In [49]:
# Xの定義
X = np.array([
    [1,2,3],
    [1,2,5],
    [1,3,4],
    [1,5,9]
])
print(X) # first column of X is a dummy （１s）

[[1 2 3]
 [1 2 5]
 [1 3 4]
 [1 5 9]]


In [51]:
# Yの定義
y = np.array([
    [1],
    [5],
    [6],
    [8]
])
print(y)

[[1]
 [5]
 [6]
 [8]]


In [55]:
# Step1
XtX = np.dot(X.T, X)
print(XtX)

[[  4  12  21]
 [ 12  42  73]
 [ 21  73 131]]


In [57]:
# Step2
XtX_inv = np.linalg.inv(XtX)
print(XtX_inv)

[[ 1.76530612 -0.39795918 -0.06122449]
 [-0.39795918  0.84693878 -0.40816327]
 [-0.06122449 -0.40816327  0.24489796]]


In [61]:
# Step3
Xty = np.dot(X.T,y)
print(Xty)

[[ 20]
 [ 70]
 [124]]


In [64]:
# Step4
w = np.dot(XtX_inv, Xty)
print(w)

[[-0.14285714]
 [ 0.71428571]
 [ 0.57142857]]


# Scikit-learn で実装

In [66]:
import sklearn

In [67]:
# Windowsの方
# !pip install scikit-learn

# Macの方
# !pip3 install scikit-learn 

In [68]:
# 重回帰分析のみ読み込み
from sklearn.linear_model import LinearRegression

In [78]:
# モデルの宣言
model = LinearRegression()
# この場合１で調節しなくていい

# １で調節する場合
# model = LinearRegression(fit_intercept = False)
# 切片がゼロになり、調節後の係数のパラメータ　がさっきの計算と同じになる　例）[[-0.14285714]　[ 0.71428571]　[ 0.57142857]]

In [79]:
# モデルの学習　＝ パラメータの調整
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [80]:
# 調整後のパラメータ
model.coef_

array([[0.        , 0.71428571, 0.57142857]])

In [81]:
model.intercept_

array([-0.14285714])

In [82]:
# 予測精度　←決定係数
model.score(X,y)

0.6923076923076926

In [84]:
# 予測値の計算
x = np.array([[1,2,3]])

In [88]:
y_pred = model.predict(x)
print(y_pred)

[[3.]]
